# Generated by Django 4.2.6 on 2023-10-31 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_animal', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_especie', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_raca', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_da_Hidrosfera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ecossistemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_eco', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('tamanho', models.FloatField()),
                ('animais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animais')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipos_da_hidrosfera')),
            ],
        ),
        migrations.AddField(
            model_name='animais',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especie'),
        ),
        migrations.AddField(
            model_name='animais',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.raca'),
        ),
    ]
