# Generated by Django 4.2.5 on 2023-11-13 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecossistemas',
            name='animais',
        ),
        migrations.AddField(
            model_name='animais',
            name='eco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ecossistemas'),
            preserve_default=False,
        ),
    ]
