# Generated by Django 4.2.5 on 2023-11-13 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_ecossistemas_animais_animais_eco'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='raca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.raca'),
            preserve_default=False,
        ),
    ]
